export { default as Home } from "./home"
export { default as Products } from "./products"
export { default as About } from "./about"
export { default as Contact } from "./contact"
export { default as Blog } from "./blog"
