export { default as Header } from "./header"
export { default as HeaderSlider } from "./header-slider"
export { default as AnimatedText } from "./animated-text"
export { default as CategoryItem } from "./category-item"
export { default as Categories } from "./categories"
export { default as Footer } from "./footer"
